### ISSUE TITLE
Make a workshop landing page?

### ISSUE THREAD

**Issue by bheavner** [UW-GAC/topmed_workshop_2017#3]
Should we make a static page linking to the rendered document to make it easier for people unfamiliar with github?

"You can build and publish Project Pages sites from the master or gh-pages branch. You can also publish your site from a /docs folder on your master branch. For more information, see "Configuring a publishing source for GitHub Pages." - https://help.github.com/articles/user-organization-and-project-pages/

**Comment by joshbis** [comment]
Seems like a good idea to me. Would this page host basic workshop information and logistics in addition to the course materials?

**Comment by smgogarten** [comment]
I think the combination of bookdown and a /docs folder would work well.
https://bookdown.org/yihui/bookdown/github.html

**Comment by smgogarten** [comment]
Landing page is now https://uw-gac.github.io/topmed_workshop_2017/
